name: checks
on:
  pull_request:
    branches:
      - main

jobs:
  commit-lint:
    runs-on: ubuntu-latest
    container:
      image: nesnds/ndp-deployment-container:3
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Copy commit-lint config
        run: cp -r /commit-lint .

      - name: Set git safe directory
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Lint commit messages
        uses: wagoid/commitlint-github-action@v5
        with:
          configFile: ./commit-lint/commitlint.config.js

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Lint Code Base
        uses: github/super-linter/slim@v4
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install
        run: npm ci

      - name: Run unit tests
        run: npm run test

